/**
 * Shared helpers for OS scheduler backends.
 *
 * Contract (all platforms):
 *   - Daily user-scope job (no admin / sudo / UAC)
 *   - Invokes: <npx> -y github:ishizakahiroshi/ai-log-clean run [--retention-days N] [--delete]
 *   - Recommended runner is always npx -y (bunx GitHub cache is sticky; see README)
 */

import { access, constants } from "node:fs/promises";
import { existsSync } from "node:fs";
import { homedir, platform } from "node:os";
import { join, dirname, delimiter, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawn } from "node:child_process";

export const GITHUB_SPEC = "github:ishizakahiroshi/ai-log-clean";
export const TASK_LABEL = "ai-log-clean";

/**
 * Build the argv that follows `npx` for a scheduled `run`.
 * @param {{ retentionDays: number, delete?: boolean }} opts
 * @returns {string[]}
 */
export function buildNpxRunArgs(opts) {
  const args = ["-y", GITHUB_SPEC, "run", "--retention-days", String(opts.retentionDays)];
  if (opts.delete) args.push("--delete");
  return args;
}

/**
 * Parse "HH:MM" (already validated by install.mjs) into hour/minute ints.
 */
export function parseAt(at) {
  const m = String(at).match(/^(\d{1,2}):(\d{2})$/);
  if (!m) throw new Error(`invalid --at value: ${JSON.stringify(at)}`);
  return {
    hour: Number.parseInt(m[1], 10),
    minute: Number.parseInt(m[2], 10),
  };
}

/**
 * Resolve an absolute path to the npx launcher.
 * Windows prefers npx.cmd (calling npx.ps1 via ShellExecute opens the editor).
 * Throws if not found — install should fail loudly rather than register a dead task.
 */
export async function resolveNpxPath() {
  const candidates = [];
  const pathEnv = process.env.PATH || "";
  const exts =
    platform() === "win32"
      ? (process.env.PATHEXT || ".COM;.EXE;.BAT;.CMD").split(";").filter(Boolean)
      : [""];

  for (const dir of pathEnv.split(delimiter)) {
    if (!dir) continue;
    if (platform() === "win32") {
      // Prefer .cmd over bare / .ps1
      for (const name of ["npx.cmd", "npx.exe", "npx"]) {
        candidates.push(join(dir, name));
      }
    } else {
      candidates.push(join(dir, "npx"));
    }
  }

  // Same directory as the running node binary (common for official Node installers)
  const nodeDir = dirname(process.execPath);
  if (platform() === "win32") {
    candidates.unshift(join(nodeDir, "npx.cmd"), join(nodeDir, "npx.exe"));
  } else {
    candidates.unshift(join(nodeDir, "npx"));
  }

  const seen = new Set();
  for (const c of candidates) {
    const abs = resolve(c);
    if (seen.has(abs)) continue;
    seen.add(abs);
    if (!existsSync(abs)) continue;
    try {
      await access(abs, constants.F_OK);
      return abs;
    } catch {
      // try next
    }
  }
  throw new Error(
    "npx not found on PATH (or next to node). Install Node.js 20+ so `npx` is available, then re-run install.",
  );
}

/**
 * Absolute path to the bundled assets/run-hidden.vbs inside this package.
 * Works for both a git checkout and an npx/github cache install.
 */
export function bundledRunHiddenVbsPath() {
  const here = dirname(fileURLToPath(import.meta.url));
  return join(here, "..", "..", "assets", "run-hidden.vbs");
}

/**
 * Windows install root: %LOCALAPPDATA%\ai-log-clean\
 * (falls back to ~/.ai-log-clean/windows/ if LOCALAPPDATA is unset)
 */
export function windowsInstallDir() {
  const base = process.env.LOCALAPPDATA || join(homedir(), ".ai-log-clean", "windows");
  return join(base, "ai-log-clean");
}

/**
 * PowerShell script body written next to run-hidden.vbs. Invoked hidden via wscript.
 * Uses the absolute npx path so PATH hijacking / missing PATH in Task Scheduler
 * sessions do not break the job.
 */
export function buildWindowsRunPs1({ npxPath, retentionDays, delete: del }) {
  const args = buildNpxRunArgs({ retentionDays, delete: del });
  // Single-quoted PowerShell literals: escape embedded ' as ''
  const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
  const argList = args.map(q).join(", ");
  return [
    "# Auto-generated by ai-log-clean install. Do not edit by hand.",
    "$ErrorActionPreference = 'Stop'",
    `$npx = ${q(npxPath)}`,
    `$args = @(${argList})`,
    "& $npx @args",
    "exit $LASTEXITCODE",
    "",
  ].join("\n");
}

/**
 * macOS LaunchAgent plist XML (UTF-8).
 */
export function buildLaunchAgentPlist({ label, npxPath, retentionDays, delete: del, at, logPath }) {
  const { hour, minute } = parseAt(at);
  const args = [npxPath, ...buildNpxRunArgs({ retentionDays, delete: del })];
  const argXml = args.map((a) => `    <string>${escapeXml(a)}</string>`).join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${escapeXml(label)}</string>
  <key>ProgramArguments</key>
  <array>
${argXml}
  </array>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Hour</key>
    <integer>${hour}</integer>
    <key>Minute</key>
    <integer>${minute}</integer>
  </dict>
  <key>StandardOutPath</key>
  <string>${escapeXml(logPath)}</string>
  <key>StandardErrorPath</key>
  <string>${escapeXml(logPath)}</string>
  <key>RunAtLoad</key>
  <false/>
</dict>
</plist>
`;
}

/**
 * Linux systemd --user unit pair.
 * @returns {{ service: string, timer: string }}
 */
export function buildSystemdUnits({ unitName, npxPath, retentionDays, delete: del, at }) {
  const { hour, minute } = parseAt(at);
  const hh = String(hour).padStart(2, "0");
  const mm = String(minute).padStart(2, "0");
  const args = buildNpxRunArgs({ retentionDays, delete: del });
  // ExecStart: executable + args. Quote paths that may contain spaces.
  const execParts = [npxPath, ...args].map(systemdQuote).join(" ");
  const service = `[Unit]
Description=ai-log-clean — trim old AI CLI session logs
Documentation=https://github.com/ishizakahiroshi/ai-log-clean

[Service]
Type=oneshot
ExecStart=${execParts}
`;
  const timer = `[Unit]
Description=ai-log-clean daily timer
Documentation=https://github.com/ishizakahiroshi/ai-log-clean

[Timer]
OnCalendar=*-*-* ${hh}:${mm}:00
Persistent=true
Unit=${unitName}.service

[Install]
WantedBy=timers.target
`;
  return { service, timer };
}

function escapeXml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** systemd unit-file quoting for a single argv token. */
export function systemdQuote(s) {
  const str = String(s);
  if (/^[A-Za-z0-9_./:=+-]+$/.test(str)) return str;
  return `"${str.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/**
 * Run an external command; capture stdout/stderr/exit code.
 * Never throws on non-zero exit (caller decides). Throws only on spawn failure.
 */
export function runCommand(command, args, opts = {}) {
  return new Promise((resolvePromise, reject) => {
    const child = spawn(command, args, {
      windowsHide: true,
      shell: Boolean(opts.shell),
      env: opts.env || process.env,
      cwd: opts.cwd,
    });
    let stdout = "";
    let stderr = "";
    if (child.stdout) child.stdout.setEncoding("utf8");
    if (child.stderr) child.stderr.setEncoding("utf8");
    child.stdout?.on("data", (d) => {
      stdout += d;
    });
    child.stderr?.on("data", (d) => {
      stderr += d;
    });
    child.on("error", reject);
    child.on("close", (code) => {
      resolvePromise({ code: code ?? 1, stdout, stderr });
    });
  });
}

/**
 * Parse a generic "Key: Value" LIST dump (schtasks /FO LIST, etc.) into a map.
 * Last occurrence wins for duplicate keys.
 */
export function parseKeyValueList(text) {
  const out = Object.create(null);
  for (const line of String(text).split(/\r?\n/)) {
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    const value = line.slice(idx + 1).trim();
    if (key) out[key] = value;
  }
  return out;
}

/**
 * Best-effort parse of date strings from OS tools into Date or null.
 * Handles ISO, en-US schtasks dumps, and ja-JP forms like
 * "2026/07/10 金 12:00:00" (weekday token ignored).
 */
export function tryParseDate(s) {
  if (s == null) return null;
  let t = String(s).trim();
  if (!t || t === "N/A" || t === "Never" || t === "なし" || /^n\/a$/i.test(t)) return null;

  // Drop localized weekday tokens: "2026/07/10 金 12:00:00" / "Fri 2026/07/10 ..."
  t = t
    .replace(
      /\s+(?:[日月火水木金土]|Sun|Mon|Tue|Wed|Thu|Fri|Sat|Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday)\s+/i,
      " ",
    )
    .replace(/\s+/g, " ")
    .trim();

  // "2026/07/10 12:00:00" → ISO-ish
  const jp = t.match(
    /^(\d{4})[\/\-.](\d{1,2})[\/\-.](\d{1,2})(?:\s+(\d{1,2}):(\d{2})(?::(\d{2}))?)?$/,
  );
  if (jp) {
    const y = Number(jp[1]);
    const mo = Number(jp[2]) - 1;
    const d = Number(jp[3]);
    const hh = Number(jp[4] || 0);
    const mm = Number(jp[5] || 0);
    const ss = Number(jp[6] || 0);
    const dt = new Date(y, mo, d, hh, mm, ss);
    return Number.isNaN(dt.getTime()) ? null : dt;
  }

  const d = new Date(t);
  return Number.isNaN(d.getTime()) ? null : d;
}

/**
 * Task Scheduler "Last Result" values that mean "never ran" / not an exit code.
 * See https://learn.microsoft.com/en-us/windows/win32/taskschd/task-scheduler-error-and-success-constants
 */
export function normalizeSchtasksLastResult(raw) {
  if (raw == null || raw === "" || raw === "N/A") return null;
  const n = Number.parseInt(String(raw), 10);
  if (!Number.isFinite(n)) return null;
  // SCHED_S_TASK_HAS_NOT_RUN = 0x41303 = 267011
  if (n === 0x41303 || n === 267011) return null;
  // Other 0x4130x status codes are scheduler state, not process exit codes
  if (n >= 0x41300 && n <= 0x41308) return null;
  return n;
}
